#Login Data
provisioning_url=https://seleniumSP.surpaassaas.com/surpaas/provision?lang=en&action=c&pid=4155&onboardType=Marketplace
#provisioning_url=https://huntersp.qaops.smartersaas.com:9000/surpaas/provision?lang=en&action=c&pid=5044&onboardType=Marketplace
email=dinesh@corenttech.com
password=Corent@123$#
acc_name=SaaSflows

#DB details
db_URL =jdbc:mysql://10.10.44.52:3306/ss447
#db_url=jdbc:mysql://10.10.44.57:3306/ss465
db_username =root
db_password =MySQL123$$